name: Deploy MkDocs Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install pillow cairosvg
      - name: Get CNAME content
        id: cname
        run: |
          if [ -f CNAME ]; then
            echo "::set-output name=content::$(cat CNAME)"
          fi
      - run: mkdocs gh-deploy --force
      - name: Restore CNAME
        if: steps.cname.outputs.content
        run: |
          echo "${{ steps.cname.outputs.content }}" > site/CNAME
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add site/CNAME
          git commit -m "Restore CNAME"
          git push